// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/blog" | "/blog/[slug]" | "/certifications" | "/dashboard" | "/datacenters" | "/docs" | "/methodology" | "/privacy" | "/sponsors" | "/status" | "/terms" | "/workloads" | "/workloads/[id]"
type AppRouteHandlerRoutes = "/api/admin/data-quality" | "/api/admin/fetch-pricing" | "/api/admin/init-db" | "/api/filters" | "/api/health" | "/api/ping" | "/api/pricing" | "/api/pricing/counts" | "/api/status" | "/api/workloads"
type PageRoutes = never
type LayoutRoutes = "/" | "/about" | "/certifications" | "/dashboard" | "/datacenters" | "/docs" | "/methodology" | "/privacy" | "/sponsors" | "/status" | "/terms" | "/workloads" | "/workloads/[id]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/api/admin/data-quality": {}
  "/api/admin/fetch-pricing": {}
  "/api/admin/init-db": {}
  "/api/filters": {}
  "/api/health": {}
  "/api/ping": {}
  "/api/pricing": {}
  "/api/pricing/counts": {}
  "/api/status": {}
  "/api/workloads": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/certifications": {}
  "/dashboard": {}
  "/datacenters": {}
  "/docs": {}
  "/methodology": {}
  "/privacy": {}
  "/sponsors": {}
  "/status": {}
  "/terms": {}
  "/workloads": {}
  "/workloads/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/about": never
  "/certifications": never
  "/dashboard": never
  "/datacenters": never
  "/docs": never
  "/methodology": never
  "/privacy": never
  "/sponsors": never
  "/status": never
  "/terms": never
  "/workloads": never
  "/workloads/[id]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
